# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-02 17:01
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('topics', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='assigned_users',
            field=models.ManyToManyField(related_name='topics', to=settings.AUTH_USER_MODEL),
        ),
    ]
