# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-02 21:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topics', '0002_topic_assigned_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='importance',
            field=models.IntegerField(choices=[(0, 'Good'), (1, 'Warning'), (2, 'Bad')], default=0),
            preserve_default=False,
        ),
    ]
