# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-01 18:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0004_auto_20170501_2009'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='is_public',
            field=models.BooleanField(default=True),
        ),
    ]
