# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-02 03:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('topics', '0001_initial'),
        ('notes', '0005_topic_is_public'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topic',
            name='parent',
        ),
        migrations.AddField(
            model_name='note',
            name='topic',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='topics.Topic'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Topic',
        ),
    ]
