# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-02 22:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0006_auto_20170502_0532'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='importance',
            field=models.IntegerField(choices=[(0, 'Good'), (1, 'Warning'), (2, 'Bad')], default=0),
            preserve_default=False,
        ),
    ]
